### ISSUE TITLE
Cannot access web interface because it crashes

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/ghorgamel#2]
After launching this tool with `npm start` it does not show anything on the web interface because the two requests for stargazers and contributors triggered HTTP 500 errors.

Error logs: 
```console
Listening at http://localhost:8080
(node:517) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
An error occured TypeError: repos.map is not a function
    at file:///home/jonas/lenra/ghorgaggre/src/server.js:56:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
An error occured TypeError: repos.map is not a function
    at file:///home/jonas/lenra/ghorgaggre/src/server.js:24:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jonas-martinez** [comment]
This seems to be fixed now.
